[package]
edition = "2018"
name = "l0dable-example"
version = "0.0.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
l0dable = { path = "../l0dable" }
panic-abort = "0.3"

[build-dependencies]
cc = "1.0"
