nix:
    stage: build
    image: nixos/nix:latest
    variables:
      GIT_SUBMODULE_STRATEGY: normal
    script:
        - nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs
        - nix-channel --update
        - nix-build
  artifacts:
    paths:
    - result/apps
    expire_in: 1 week
