[workspace]
members = [
  "max32665",
  "card10",
  "l0dable",
  "watchapp",
  "example",
]

[profile.release]
codegen-units = 1
incremental = false
debug = true
opt-level = "s"
lto = true
panic = "abort"
