[workspace]
members = [
  "card10-sys",
  "card10-alloc",
  "card10-l0dable",
  "example",
  "rkanoid",
]

default-members = [
  "example",
  "rkanoid",
]

[profile.release]
codegen-units = 1
incremental = false
debug = true
opt-level = "s"
lto = true
panic = "abort"
