[package]
edition = "2018"
name = "l0dable"
version = "0.0.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
r0 = "0.2"
panic-abort = "0.3"

[build-dependencies]
cc = "1.0"
bindgen = "0.51"