#!/usr/bin/env bash

set -e

cargo build --release
arm-none-eabi-objcopy -O binary target/thumbv7em-none-eabi/release/$2 card10.bin
python c/bootloader/crc_patch.py card10.bin

echo "Copy this file to the device in USB Mass Storage mode:"
ls -l card10.bin
