[package]
edition = "2018"
name = "l0dable-rkanoid"
version = "0.0.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
card10-l0dable = { path = "../card10-l0dable" }

[build-dependencies]
cc = "1.0"

[[bin]]
name = "rkanoid"
path = "src/main.rs"
